all:
	g++ -Wall -std=c++2a -march=native MyuintLauncher.cpp -o ex3 -ggdb3
	g++ -Wall -std=c++2a -march=native fib.cpp -o fib -ggdb3
	g++ -Wall -std=c++2a -march=native rule110.cpp -o rule110 -ggdb3
	g++ -Wall -std=c++2a -march=native test.cpp -o test -ggdb3
